config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :bookings do
    member do
      resources :charges
    end
  end

  
  resources :products
  get 'users/show'
  get 'pages/sellproduct'


  resources :posts do
    resources :comments
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
end
  root 'pages#home'
  get 'seller_dashboard', to: 'pages#seller_dashboard'
  get 'buyer_dashboard', to: 'pages#buyer_dashboard'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :product
  belongs_to :user

  # Scoping allows you to specify commonly-used queries which can be referenced as method calls on the association objects or models.
  # A scope is a subset of a collection.

  scope :approved, -> { where(approved: true, paid: false) }
  scope :paid, -> { where(paid: true) }
  scope :pending, -> { where(approved: false) }

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(booking_params)
    @booking.user_id = current_user.id

    respond_to do |format|
      if @booking.save
        #BookingMailer.booking_confirmation(@booking).deliver 
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:product_id, :user_id, :number, :approved)
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
 <!-- form_for creates a form that allows the user to create or update the attributes of a specific model object. -->

<%= form_for(booking) do |f| %>
  <% if booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <% if params[:product_id].present? %>
      <%= f.hidden_field :product_id, value: params[:product_id] %>
    <% end %>
  </div>

  <br><br><br>

  <div class="field">
    <%= f.label :number_you_wish_to_buy?  %>
    <%= f.number_field :number %>
  </div>

  <p>If you own this booking would you like to approve it?</p>

  <div class="field">
    <%= f.label :approved %>
    <%= f.check_box :approved %>
  </div>
<br><br><br>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<div class="registration-bg">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="log-in panel">
          <div class="panel-heading">

<h1>Update Your Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

            </div>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/bookings/index.html.erb
<div class="registration-bg">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="log-in panel">
          <div class="panel-heading">

<p id="notice"><%= notice %></p>

<h1>Your Bookings</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Cost ($USD)</th>
      <th>Product</th>
      <th>User</th>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.product.title %></td>
        <td><%= number_to_currency(booking.product.price) %></td>
        <td><%= booking.product.title %></td>
        <td><%= booking.user.email %></td>
        <td><%= booking.number %></td>
        <td><%= link_to 'Show', booking %></td>
        <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
        <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Make A New Booking', new_booking_path, class: 'btn btn-primary'  %><br>
<br>
<%= link_to 'Click here to make payment', buyer_dashboard_path, class: 'btn btn-success' %>

              </div>
            </div>
           </div>
          </div>
        </div>
      </div>

app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Back', bookings_path %>

app/views/bookings/show.html.erb
<div class="registration-bg">
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-md-offset-4">
        <div class="log-in panel">
          <div class="panel-heading">

<h2>You Have Booked:</h2>

<!-- displays the booking made by the user and provides a payment button to finalise transaction -->

<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @booking.product.title %>
</p>

<p>
  <strong>You are logged in as:</strong>
  <%= @booking.user.email %>
</p>

<p>
  <strong>How many would you like to order:</strong>
  <%= @booking.number %>
</p>

<p>
  <strong>Price per unit:</strong>
  <%= number_to_currency(@booking.product.price) %>
</p>

<%= link_to 'Click here to make payment', buyer_dashboard_path, class: 'btn btn-success' %>

<br><br>



<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>

            </div>
          </div>
        </div>
      </div>
    </div>
</div>