config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :bookings do
    member do
      resources :charges
    end
  end

  
  resources :products
  get 'users/show'
  get 'pages/sellproduct'


  resources :posts do
    resources :comments
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
end
  root 'pages#home'
  get 'seller_dashboard', to: 'pages#seller_dashboard'
  get 'buyer_dashboard', to: 'pages#buyer_dashboard'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :product
  belongs_to :user

  # Scoping allows you to specify commonly-used queries which can be referenced as method calls on the association objects or models.
  # A scope is a subset of a collection.

  scope :approved, -> { where(approved: true, paid: false) }
  scope :paid, -> { where(paid: true) }
  scope :pending, -> { where(approved: false) }

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments 
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :bookings

  validates :title, presence: true , length: { minimum: 2 }

  mount_uploaders :images, ImageUploader

end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :booking

  after_create :update_booking

  def update_booking
    booking.update_attributes(paid: true)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments
  has_many :posts
  has_many :products
  has_many :bookings

  enum role: [:user, :editor, :admin]
	after_initialize :set_default_role, :if => :new_record?

	def set_default_role
		self.role ||= :user
	end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

         def self.from_omniauth(auth)
           where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
             user.email = auth.info.email
             user.password = Devise.friendly_token[0,20]
             #user.name = auth.info.name   # assuming the user model has a name
             #user.image = auth.info.image # assuming the user model has an image
             # If you are using confirmable and the provider(s) you use validate emails,
             # uncomment the line below to skip the confirmation emails.
             # user.skip_confirmation!
           end
         end

         def self.new_with_session(params, session)
          super.tap do |user|
            if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
              user.email = data["email"] if user.email.blank?
            end
          end
        end



end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
	def new
  end

	def create
		@booking = Booking.find(params[:id])
	  # Amount in cents
	  @amount = (@booking.product.price * 100).to_i

	  customer = Stripe::Customer.create(
	    :email => params[:stripeEmail],
	    :source  => params[:stripeToken]
	  )

	  charge = Stripe::Charge.create(
	    :customer    => customer.id,
	    :amount      => @amount,
	    :description => "Booking id: #{@booking.id}",
	    :currency    => 'usd'
	  )

		@transaction = Transaction.create(amount: @amount,
			user_id: current_user.id, booking_id: @booking.id)


	rescue Stripe::CardError => e
	  flash[:error] = e.message
	  redirect_to buyer_dashboard_path
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def seller_dashboard
    # get approved and not yet approved bookings from products listed for sale by the seller
    # render template for that host
    @products = current_user.products
  end

  def buyer_dashboard
    # bookings made by the user which are both paid and unpaid 
    @bookings = current_user.bookings
    @approved_bookings = @bookings.approved
    @pending_bookings = @bookings.pending
    @paid_bookings = @bookings.paid
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments # to show all posts
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    authorize @post
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :user_id)
      #params.require(:post).permit(policy(@post).permitted_attributes)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized

  def index
    @users = User.all
    authorize User
  end

  def show
    @user = User.find(params[:id])
    #authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    #authorize user
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def yes_no(input)
		# if input
		# 	'yes'
		# else
		# 	'no'
		# end

		input ? 'yes' : 'no'
	end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # def full_name
  #   @user.first_name + " " + @user.last_name
  # end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Project2</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'partials/nav' %>



      <%= yield %>





    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/admin_dashboard.html.erb
<h1>Admin Dashboard</h1>

<!-- add user who booked a booking -->

<h3>My Bookings</h3>

<table class="table">
  <thead>
    <tr>
      <th>Cost ($USD)</th>
      <th>Product ID</th>
      <th>User ID</th>
      <th>Number</th>
      <th>Approved?</th>
    </tr>
  </thead>
  <tbody>
		<% @products.each do |product| %>
			<% product.bookings.each do |booking| %>
				<tr>
          <td><%= number_to_currency(booking.product.price) %></td>
	        <td><%= booking.product_id %></td>
	        <td><%= booking.user_id %></td>
	        <td><%= booking.number %></td>
	        <td><%= yes_no(booking.approved) %></td>
	        <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
	      </tr>
			<% end %>
		<% end %>
  </tbody>
</table>

app/views/pages/buyer_dashboard.html.erb
<div class="registration-bg">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="log-in panel">
          <div class="panel-heading">

<h1>Buyer Dashboard</h1>

<h3>Ready for Payment</h3>

<table class="table table-striped">
	<thead>
		<tr>
			<th>Number</th>
			<th>Price</th>
			<th>Title</th>
			<th>Pay</th>
		</tr>
	</thead>
	<tbody>
		<% @approved_bookings.each do |booking| %>
			<tr>
				<td><%= booking.number %></td>
				<td><%= number_to_currency(booking.product.price) %></td>
				<td><%= booking.product.title %></td>
				<td><%= render 'partials/stripe', booking: booking %></td>
			</tr>
		<% end %>
	</tbody>
</table>

<h3>Already Paid</h3>

<table class="table">
	<thead>
		<tr>
			<th>Number</th>
			<th>Price</th>
			<th>Title</th>
		</tr>
	</thead>
	<tbody>
		<% @paid_bookings.each do |booking| %>
			<tr>
				<td><%= booking.number %></td>
				<td><%= number_to_currency(booking.product.price) %></td>
				<td><%= booking.product.title %></td>
			</tr>
		<% end %>
	</tbody>
</table>

<!-- <h3>Pending Approval</h3>

<table class="table">
	<thead>
		<tr>
			<th>Number</th>
			<th>Price</th>
			<th>Title</th>
		</tr>
	</thead>
	<tbody>
		<%# @pending_bookings.each do |booking| %>
			<tr>
				<td><%#= booking.number %></td>
				<td><%#= number_to_currency(booking.product.price) %></td>
				<td><%#= booking.product.title %></td>
				<td>You will be able to make payment once approval granted</td>
			</tr>
		<%# end %>
	</tbody>
</table> -->

					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/pages/customer_dashboard.html.erb
<h1>Customer Dashboard</h1>

<h3>Ready for Payment</h3>

<table class="table">
	<thead>
		<tr>
			<th>Number</th>
			<th>Price</th>
			<th>Title</th>
			<th>Pay</th>
		</tr>
	</thead>
	<tbody>
		<% @approved_bookings.each do |booking| %>
			<tr>
				<td><%= booking.number %></td>
				<td><%= number_to_currency(booking.product.price) %></td>
				<td><%= booking.product.title %></td>
				<td><%= render 'partials/stripe', booking: booking %></td>
			</tr>
		<% end %>
	</tbody>
</table>

<h3>Already Paid</h3>

<table class="table">
	<thead>
		<tr>
			<th>Number</th>
			<th>Price</th>
			<th>Title</th>
		</tr>
	</thead>
	<tbody>
		<% @paid_bookings.each do |booking| %>
			<tr>
				<td><%= booking.number %></td>
				<td><%= number_to_currency(booking.product.price) %></td>
				<td><%= booking.product.title %></td>
				<td><%= render 'partials/stripe' %></td>
			</tr>
		<% end %>
	</tbody>
</table>

<h3>Pending Approval</h3>

<table class="table">
	<thead>
		<tr>
			<th>Number</th>
			<th>Price</th>
			<th>Title</th>
		</tr>
	</thead>
	<tbody>
		<% @pending_bookings.each do |booking| %>
			<tr>
				<td><%= booking.number %></td>
				<td><%= number_to_currency(booking.product.price) %></td>
				<td><%= booking.product.title %></td>
				<td>You will be able to make payment once approval granted</td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Yes You Can!</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<style>
.jumbotron {
    background-image: url("http://s1.1zoom.me/big0/975/USA_Bridges_Bay_450686.jpg");
    font-family: Montserrat, sans-serif;
    height: 50%;
  }

  </style>

</head>

<div class="jumbotron text-center">
  <h1 id="welcome">The Official USA Citizenship Marketplace</h1>
  <p id="choice">Buy a new life or sell your old one</p>

  <% if user_signed_in? %>
    <%= link_to 'Logout', destroy_user_session_path, :method => :delete, class: 'btn btn-primary' %>
  <% else %>
    <%= link_to 'Login', new_user_session_path, class: 'btn btn-default' %>
    <%= link_to 'Join', new_user_registration_path, class: 'btn btn-primary' %>
  <% end %><br><br><br>

</div>


<!-- Container (About Section) -->
<div id="newlife" class="container-fluid">
  <div class="row">
      <div class="col-md-offset-4 col-md-4 col-md-offset-4">
      <h2 id="create">We will help you create a new life!</h2>
      <br>
      <br>
      <p><span class="glyphicon glyphicon-tower"></span>
        Recent legislative changes mean Non US Citizens can now purchase brand new, government issued, life time USA citizenship for only <strong>USD$250,000</strong>.</p>
      <br>
      <p><span class="glyphicon glyphicon-tower"></span>
        At the start of every calendar year the USA government will provide a finite number of "citizenship slots". We are the USA government's only
        approved citizenship seller. You can obtain USA citizenship by no other means than through our website.</p>
      <br>
      <p><span class="glyphicon glyphicon-tower"></span>
        Once these citizenship slots are exhausted, no more will be offered by the government until the start of the next calendar year.</p>
      <br>
      <p><span class="glyphicon glyphicon-tower"></span>
        Demand is expected to be high so the annual allocation may be exhausted in a matter of weeks or months.</p>
      <br>
      <p><span class="glyphicon glyphicon-tower"></span>
        Dual citizens who hold valid USA citizenship are now able to
        renounce and sell their USA citizenship via this site only once the government issued annual allocation has been exhausted.</p>
      </div>
      <br>
      <br>
      <br>
      <div class="row">
        <div class="col-lg-12">
          <img src="http://houstonlibrary.org/sites/default/files/anchor_service_passport.png" class="img-circle" alt="USA passport">
        </div>
      </div>
    </div>
  </div>
</div>
</div>
</div>
<br><br><br>

<!-- Process Section) -->
<div id="how" class="container-fluid text-center">
  <h2 id="process">How Does this Work?</h2><br>
  <div class="row text-center ">
    <div class="col-lg-3 col-sm-3 col-xs-12">
      <div class="thumbnail">
        <img src="https://dl.dropbox.com/s/hker526udb5jhl6/step1.jpg" alt="Step 1" >
        <h1 class="bigstep"><strong>JOIN</strong></h1>
        <p>Create an account</p>
      </div>
    </div>
    <div class="col-lg-3 col-sm-3 col-xs-12">
      <div class="thumbnail">
        <img src="https://dl.dropbox.com/s/22mkhjbzwiyl9ar/step2.jpg" alt="Step 2" ><br>
        <h1 class="bigstep"><strong>ADD</strong></h1>
        <p>Add citizenship slot to your cart</p>
      </div>
    </div>
    <div class="col-lg-3 col-sm-3 col-xs-12">
      <div class="thumbnail">
        <img src="https://dl.dropbox.com/s/765iixywz55cosr/step3.jpg" alt="Step 3" ><br>
        <h1 class="bigstep"><strong>PAY</strong></h1>
        <p>Make payment via card</p>
      </div>
    </div>
    <div class="col-lg-3 col-sm-3 col-xs-12">
      <div class="thumbnail">
        <img src="https://dl.dropbox.com/s/t9rxr1fw1407ncx/step4.jpg" alt="Step 4" ><br>
        <h1 class="bigstep"><strong>CLEAR</strong></h1>
        <p>Payment clears, we email you forms</p>
      </div>
    </div>
  </div>
      <div class="row text-center">
      <div class="col-lg-3 col-sm-3 col-xs-12">
        <div class="thumbnail">
          <img src="https://dl.dropbox.com/s/4h7dkb120uuy1xu/step-5.jpg" alt="Step 5" ><br>
          <h1 class="bigstep"><strong>SECURITY</strong></h1>
          <p>Forms come back, security check starts</p>
        </div>
      </div>
        <div class="col-lg-3 col-sm-3 col-xs-12">
          <div class="thumbnail">
            <img src="https://dl.dropbox.com/s/0wwk1wint1vl7yz/step-6.jpg" alt="Step 6" ><br>
            <h1 class="bigstep"><strong>APPROVED</strong></h1>
            <p>Check finished, all clear</p>
          </div>
        </div>
          <div class="col-lg-3 col-sm-3 col-xs-12">
            <div class="thumbnail">
              <img src="https://dl.dropbox.com/s/t7nrbjlcd7146vc/step-7.jpg" alt="Step 7" ><br>
              <h1 class="bigstep"><strong>PASSPORT</strong></h1>
              <p>We mail out your new passport</p>
            </div>
          </div>
            <div class="col-lg-3 col-sm-3 col-xs-12">
              <div class="thumbnail">
                <img src="https://dl.dropbox.com/s/vfjontj1bwbikvv/step-8.jpg" alt="Step 8" ><br>
                <h1 class="bigstep"><strong>ARRIVAL</strong></h1>
                <p>Live and work in the USA</p>
              </div>
      </div>
    </div>
  </div>


    <!-- LOCATION GALLERY SECTION -->
  </div>
</div><br>
<div class="block">
<h2>Live Anywhere in the USA You Wish</h2><br>
<p class="lead">Here is some inspiration.</p></h2>
  <div class="row">
    <div class="col-lg-4 col-sm-6 col-xs-12">
        <a href="#">
             <img src="https://www.moma.org/wp/inside_out/wp-content/uploads/2010/06/Chicago.jpg" class="thumbnail img-responsive">
        </a>
    </div>
     <div class="col-lg-4 col-sm-6 col-xs-12">
        <a href="#">
             <img src="https://upload.wikimedia.org/wikipedia/commons/1/1a/Harper_Midway_Chicago.jpg" class="thumbnail img-responsive">
        </a>
    </div>
     <div class="col-lg-4 col-sm-6 col-xs-12">
        <a href="#">
             <img src="http://www.la-palma-tourismus.com/Jacomo/upload/la-palma_puerto-naos1.jpg" class="thumbnail img-responsive">
        </a>
    </div>
     <div class="col-lg-4 col-sm-6 col-xs-12">
        <a href="#">
             <img src="http://www.diszine.com/wp-content/uploads/2011/06/sleeping-beauty-castle-at-disneyland.jpg" class="thumbnail img-responsive">
        </a>
    </div>
     <div class="col-lg-4 col-sm-6 col-xs-12">
        <a href="#">
             <img src="http://www.travelreviewshistoricsites.com/images/mount-rushmore-sculpture-lg.jpg" class="thumbnail img-responsive">
        </a>
    </div>
     <div class="col-lg-4 col-sm-6 col-xs-12">
        <a href="#">
             <img src="https://s-media-cache-ak0.pinimg.com/originals/c4/f5/46/c4f54619b6f91bd690f552cad74e4673.jpg" class="thumbnail img-responsive">
        </a>
    </div>
     <div class="col-lg-4 col-sm-6 col-xs-12">
        <a href="#">
             <img src="http://cdn4.hotelopia.com/giata/bigger/01/014726/014726a_hb_a_043.jpg" class="thumbnail img-responsive">
        </a>
    </div>
     <div class="col-lg-4 col-sm-6 col-xs-12">
        <a href="#">
             <img src="http://c.ymcdn.com/sites/www.itsmfusa.org/resource/group/b6661cec-40eb-4034-965b-608ed0312a7f/new_york_city_at_night.jpg" class="thumbnail img-responsive">
        </a>
    </div>
     <div class="col-lg-4 col-sm-6 col-xs-12">
        <a href="#">
             <img src="http://www.taketours.com/images/logo/7208.jpg" class="thumbnail img-responsive">
        </a>
    </div>
  </div>
</div>
  <hr>

<div id="contact" class="container-fluid">
  <h2 id="details" class="text-center">CONTACT</h2>
  <div class="row">
    <div class="col-sm-12">
      <p class="cd">Contact us and we'll get back to you within 24 hours.</p>
      <p class="cd"><span class="glyphicon glyphicon-map-marker"></span> Sydney, AU</p>
      <p class="cd"><span class="glyphicon glyphicon-phone"></span> +61 2 9999 9999</p>
      <p class="cd"><span class="glyphicon glyphicon-envelope"></span> admin@usacm.org</p>
    </div>
  </div>
</div>

app/views/pages/seller_dashboard.html.erb
<div class="registration-bg">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="log-in panel">
          <div class="panel-heading">

<h1>Sellers Dashboard</h1>

<!-- add user who booked a booking -->

<h3>My Sales</h3>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Cost ($USD)</th>
      <th>Product</th>
      <th>User Email</th>
      <th># of Units</th>
      <th>Approved?</th>
    </tr>
  </thead>
  <tbody>
		<% @products.each do |product| %>
			<% product.bookings.each do |booking| %>
				<tr>
          <td><%= number_to_currency(booking.product.price) %></td>
	        <td><%= booking.product.title %></td>
	        <td><%= booking.user.email %></td>
	        <td><%= booking.number %></td>
	        <td><%= yes_no(booking.approved) %></td>
	        <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
	      </tr>
			<% end %>
		<% end %>
  </tbody>
</table>

            </div>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/pages/sellproduct.html.erb
<h2>Products</h2>

<!-- makes a table listing products for sale, users can click the 'show' button if they want to see more -->

<table>
  <thead>
    <tr>
      <th>Price</th>
      <th>Title</th>
      <th>Description</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% current_user.products.each do |product| %>
      <tr>
        <td><%= product.price %></td>
        <td><%= product.title %></td>
        <td><%= product.description %></td>
        <td><%= product.user.email %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/partials/_nav.html.erb
<!-- NAVBAR -->

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href= '#' class="navbar-brand">U.S.A.C.M</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'Forum', posts_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to 'Buy USA Citizenship', products_path %></li>
          <li><%= link_to 'Sell USA Citizenship', new_product_path %></li>
          <li><a href="/buyer_dashboard">Buyer Dashboard</a></li>
          <li><a href="/seller_dashboard">Seller Dashboard</a></li>
        <% else %>
        <% end %>

      </ul>
      <ul class="nav navbar-nav navbar-right">

<!-- user sign up / sign in / sign out different functionality depending on whether logged in or not -->
      <% if user_signed_in? %>
        <li>
          <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
        </li>
        <li>
          <%= link_to(current_user.email, edit_user_registration_path) %>
        </li>
      <% else %>
        <li>
          <%= link_to('Login', new_user_session_path)  %>
        </li>
        <li>
          <%= link_to('Sign Up', new_user_registration_path)  %>
        </li>
      <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/partials/_stripe.html.erb
<%= form_tag charges_path(booking.id) do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Booking for: <%= booking.product.title %>"
          data-amount="<%= booking.product.price * 100 %>"
          data-locale="auto"></script>
<% end %>

app/views/partials/_user.html.erb
<!-- <td>
  <%#= link_to 'user', @user.email  %>
</td> -->
<td>
  <%= form_for @users do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <td>
    <button><%= f.submit 'Change Role' %></button>
    </td>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button') unless user == current_user %>
</td>