config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :bookings do
    member do
      resources :charges
    end
  end

  
  resources :products
  get 'users/show'
  get 'pages/sellproduct'


  resources :posts do
    resources :comments
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
end
  root 'pages#home'
  get 'seller_dashboard', to: 'pages#seller_dashboard'
  get 'buyer_dashboard', to: 'pages#buyer_dashboard'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :bookings

  validates :title, presence: true , length: { minimum: 2 }

  mount_uploaders :images, ImageUploader

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json

  def sellproduct
    @sellproduct = current_user.products
  end

  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:price, :title, :description, :user_id, {images: []})
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class="registration-bg">
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-md-offset-4">
        <div class="log-in panel">
          <div class="panel-heading">

            <h2>List your USA Citizenship for Sale</H2><br><br>

<!-- form_for creates a form that allows the user to create or update the attributes of a specific model object. -->


<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="panel-body">
    <%= f.label :price %>
    <%= f.number_field :price, autofocus: true, class: 'form-control', required: true %>
  </div><br><br>

  <div class="panel-body">
    <%= f.label :title %>
    <%= f.text_field :title, autofocus: true, class: 'form-control', required: true %>
  </div><br><br>

  <div class="panel-body">
    <%= f.label :description %>
    <%= f.text_area :description, autofocus: true, class: 'form-control', required: true %>
  </div><br><br>

  <div class="field">
    <%= f.label :images %>
    <%= f.file_field :images, multiple: true %>
  </div>


  <div class="panel-body">
    <%= f.submit "List my citizenship for sale", class: "btn-lg btn-info btn-block" %>
  </div>
<% end %>
<br><br><br>

              </div>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="registration-bg">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="log-in panel">
          <div class="panel-heading">

<p id="notice"><%= notice %></p>

<h1>Buy USA Citizenship</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Price</th>
      <th>Title</th>
      <th>Description</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= number_to_currency(product.price) %></td>
        <td><%= product.title %></td>
        <td><%= product.description %></td>
        <td><%#= product.user.email %></td>
        <td><%= link_to 'Show', product %></td>

        <td><%= link_to 'Edit', edit_product_path(product) if current_user.admin? %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } if current_user.admin? %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

<%= link_to 'Dual Citizen? List your USA citizenship for sale', new_product_path %>

                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

app/views/products/new.html.erb
<!-- <h1>New Product</h1> -->

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path, class: "btn-lg btn-info btn-block"  %>

app/views/products/show.html.erb
<div class="registration-bg">
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-md-offset-4">
        <div class="log-in panel">
          <div class="panel-heading">

<p id="notice"><%= notice %></p>

<h2>Buy USA Citizenship</h2>

<p>
  <strong>Price:</strong>
  <%= number_to_currency(@product.price) %>
</p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<!-- <p>
  <strong>User:</strong> -->
  <%#= @product.user.email  %>
<!-- </p> -->

<%= link_to 'Add to Cart', new_booking_path(product_id: @product.id), class: 'btn btn-primary' %>

<% @product.images.each do |image| %>
  <img src="<%= image.url %>">
<% end %>
<br><br>
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>